#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=423BdebGorep
#SBATCH --ntasks-per-node=10
#SBATCH --output=output423BdebGorep.out
#SBATCH -o outfile423BdebGorep.log 
#SBATCH -e errfile423BdebGorep.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Pyth
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba25B
cd /home/thomas.batard/SeminarioTesis2/Prueba42B

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


#python Cluster_Prueba42_DIP_0B_debU_30K.py
#python Cluster_Prueba42_UnknownOperatorV4_1B.py
#python Cluster_Prueba42_UnknownOperatorV4OPP_2B.py
#python Cluster_Prueba42_UnknownOperatorV4_1B_debG_30K.py


#python Cluster_Prueba42_UnknownOperatorV4OPP_2B_29K.py

python Cluster_Prueba42_UnknownOperatorV4OPP_3B_29K_25.py

date
