#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=470BBdebUsnOpp
#SBATCH --ntasks-per-node=10
#SBATCH --output=output470BBdebUsnOpp.out
#SBATCH -o outfile470BBdebUsnOpp.log 
#SBATCH -e errfile470BBdebUsnOpp.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Pyth
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba25B
cd /home/thomas.batard/SeminarioTesis2/Prueba47B

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


python Cluster_Prueba47_VectorialTotalVariationOPP_0B_30K_snWopp.py


date

