#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=Den295B
#SBATCH --ntasks-per-node=10
#SBATCH --output=output295Bden.out
#SBATCH -o outfileden295B.log 
#SBATCH -e errfileden295B.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Python
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba25B
cd /home/thomas.batard/SeminarioTesis2/Prueba29B

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py

#python Cluster_Prueba29_UnknownOperatorV4OPP_2B.py
#python Cluster_Prueba29_UnknownOperatorV4OPP_3B_SGD.py
#python Cluster_Prueba29_UnknownOperatorV4OPP_4B_adam.py
python Cluster_Prueba29_UnknownOperatorV4OPP_5B_LBFS.py

date
