#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=461BdebGesp
#SBATCH --ntasks-per-node=10
#SBATCH --output=output461BdebGesp.out
#SBATCH -o outfile461BdebGesp.log 
#SBATCH -e errfile461BdebGesp.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Pyth
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba25B
cd /home/thomas.batard/SeminarioTesis2/Prueba46B

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


#python Cluster_Prueba46_GradientRiemannianNewOPP_0B_debG_28K.py
python Cluster_Prueba46_UnknownOperatorV4_1B_debG_27K.py
#python Cluster_Prueba46_DIPOPP_2B_sinpesoOpp.py


date

