#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=433Bden15esp
#SBATCH --ntasks-per-node=10
#SBATCH --output=output433Bden15esp.out
#SBATCH -o outfile433Bden15esp.log 
#SBATCH -e errfile433Bden15esp.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Pyth
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba25B
cd /home/thomas.batard/SeminarioTesis2/Prueba43B

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


#python Cluster_Prueba43_UnknownOperatorV4_0B_den15_10K.py
#python Cluster_Prueba43_UnknownOperatorV4OPP_1B_den15_10K.py
#python Cluster_Prueba43_DIP_2B_den15_10K.py
python Cluster_Prueba43_DIPOPP_3B_den15_10K.py

date

