#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=401Bden25esp
#SBATCH --ntasks-per-node=10
#SBATCH --output=output401Bden25esp.out
#SBATCH -o outfile401Bden25esp.log 
#SBATCH -e errfile401Bden25esp.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Pyth
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba25B
cd /home/thomas.batard/SeminarioTesis2/Prueba40B

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


#python Cluster_Prueba40_DIP_0B_den25_8K.py
python Cluster_Prueba40_DIPOPP_1B_den25_8K.py
#python Cluster_Prueba40_UnknownOperatorV4OPP_2B.py
#python Cluster_Prueba40_DIPOPP_3B.py

date
