#!/bin/bash

#SBATCH --partition=GPU
#SBATCH --job-name=442BdebGrep
#SBATCH --ntasks-per-node=10
#SBATCH --output=output442BdebGrep.out
#SBATCH -o outfile442BdebGrep.log 
#SBATCH -e errfile442BdebGrep.txt

#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=natalia.huitzil@cimat.mx
#

# exportar el path hacia los ejecutables de Pyth
export PATH=$PATH:/opt/anaconda3_titan/bin
source /home/est_posgrado_natalia.huitzil/.bashrc
conda activate compu21

hostname
date
# Ejecutar script

#cd /home/est_posgrado_natalia.huitzil/ST2/Prueba25B
cd /home/thomas.batard/SeminarioTesis2/Prueba44B

#cd /home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8
#cd/home/est_posgrado_natalia.huitzil/.conda/envs/myenv/bin/python3.8 runner.py
#/home/est_posgrado_natalia.huitzil/.conda/envs/compu21/bin/python3.8 Cluster_Prueba7_Denoising3curvGaussian.py


#python Cluster_Prueba44_GradientRiemannianNewOPP_0B_debG_30K.py
#python Cluster_Prueba44_DIP_1B_debG_13K.py
python Cluster_Prueba44_DIPOPP_2B_debG_13K.py

date

